version: '3'  

services:  
  db:  
    image: postgres:latest  
    restart: always  
    environment:  
      POSTGRES_USER: leyla
      POSTGRES_PASSWORD: 123456  
      POSTGRES_DB: todolist2 


    volumes:  
      - postgres_data2:/var/lib/postgresql/data/  

  web:  
    build: .
#    command: python manage.py migrate &&  gunicorn todolist.wsgi:application --bind 0.0.0.0:8000  
    command: >
      sh -c "python manage.py migrate &&  gunicorn todolist.wsgi:application --bind 0.0.0.0:8000"
#    volumes:  
#      - ./:/app  # Mount the django_app directory  
    ports:  
      - "8000:8000"  
    depends_on:  
      - db  

volumes:  
  postgres_data2:
