version: '3'  

services:  
  db:  
    image: postgres:latest 
    restart: always  
    environment:  
      POSTGRES_USER: leyla  
      POSTGRES_PASSWORD: 123456 
      POSTGRES_DB: todolist 
    volumes:  
      - postgres_data:/var/lib/postgresql/data  
    ports:  
      - "5432:5432"  
  app:
#    build: .  
    image: php8.4-fpm
    container_name: todo-list-api  
    ports:  
      - "8000:8000"  
    volumes:  
      - .:/app
    command: >
      sh -c "php artisan migrate  && php artisan serve --host=0.0.0.0 --port 8000"
    depends_on:  
      - db  
    environment:  
      - DB_CONNECTION=pgsql  
      - DB_HOST=db  
      - DB_PORT=5432  
      - DB_DATABASE=todolist 
      - DB_USERNAME=leyla  
      - DB_PASSWORD=123456 
#  nginx:
#    image: nginx:alpine
#    container_name: nginx-server
#    restart: unless-stopped
#    ports:
#      - 81:80
#    volumes:
#      - ./:/var/www/html
#      - ./default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - app

volumes:  
  postgres_data:
