apiVersion: v1
kind: ConfigMap
metadata:
  name: python-config
  namespace: prod
  labels:
    app: python-django
data:
  DJANGO_DEBUG: "False"                  # حالت Debug را غیرفعال کنید برای تولید  
  DATABASE_URL: "postgres://leyla:123456@db:5432/todolist2"  # URL پایگاه داده PostgreSQL  
  ALLOWED_HOSTS: ".enginedevops.ir, localhost"  
