---
- name: Update Kubernetes Deployment
  hosts: master 
  tasks:
    - name: Set image for deployment
      command: kubectl set image deployment/react-front react-front=enginedevops/react-jenkins:{{ HASH_COMMIT }}  -n prod
      register: result

    - name: Print result
      debug:
        var: result.stdout
