apiVersion: v1
kind: Service
metadata:
  name: react-todolist-chrome 
  namespace: prod
  labels:
    app: react-todolist-chrome
spec:
  type: LoadBalancer
  ports:
   - port: 3000
  selector:
   app: react-todolist-chrome
