apiVersion: v1
kind: ConfigMap
metadata:
  name: java-config
  namespace: prod
  labels:
    app: java-spring
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/todolist"
  SPRING_DATASOURCE_USERNAME: leyla  
  SPRING_DATASOURCE_PASSWORD: "123456"
