apiVersion: traefik.containo.us/v1alpha1  
kind: IngressRoute  
metadata:  
  name: react-front 
  namespace: prod 
spec:  
  entryPoints:  
    - web  
  routes:  
#    - match: Host(`enginedevops.ir`)  
    - match: PathPrefix(`/`)  
      kind: Rule  
      services:  
        - name: react-front
          port: 3000
